# -*- coding: utf-8 -*-

class RuleSet(object):
  """
  Tune the weights for accuracy
  """
  score_weights = {
    'char': 1,
    'word': 1.3,
    'segment': 1,
    'rule': 1,
    'hint': 2,
  }

  """
  List of supported languages (supported in some capacity)
  """
  language_list = [u'fr', u'en', u'de', u'it', u'da', u'fi', u'es', u'ru',
                  u'nl', u'pt', u'no', u'tr', u'sv', u'ro', u'pl']

  """
  Full alphabet for each language
  """
  alphabets = {
    u'no': u'ABCDEFGHIJKLMNOPQRSTUVWXYZÆØÅabcdefghijklmnopqrstuvwxyzæøå',
    u'sv': u'ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖabcdefghijklmnopqrstuvwxyzåäö',
    u'fi': u'ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖabcdefghijklmnopqrstuvwxyzåäö',
    u'da': u'ABCDEFGHIJKLMNOPQRSTUVWXYZÆØÅabcdefghijklmnopqrstuvwxyzæøå',
    u'en': u'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',
    u'de': u'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÄäÖöÜüß',
    u'nl': u'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',
    u'pt': u'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzáâãàçéêíóôõú',
    u'es': u'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzñ',
    u'fr': u'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzàâîïûéèêôùÿ',
    u'it': u'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',
    u'pl': u'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzŁńśź',
    u'tr': u'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzığş',
    u'ro': u'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzășț',
    u'ru': u'АаБбВвГгДдЕеЁёЖжЗзИиЙйКкЛл†МмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЫыЬьЭэЮюЯя',
  }

  """
  List of word rules in regex form
  """
  word_rules = {
    u'es': [
      r'\wtas?\b', # match ta or tas word ending
      r'\wtos?\b', # match to or tos word ending
      r'\wrros?\b' # match rros word ending
      r'hi[a|e|i|o|u]' # match 'hi' followed by a vowel
    ],

    u'de': [
      r'\wen\b', # match 'en' word ending
    ],
  }

  """
  List of common word segments in each language
  """
  word_segments = {
    u'es': [u'gu', u'gü', u'hi', u'hu', u'll', u'que', u'qui', u'rr'],
    u'nl': [u'ij', u'ik'],
    u'da': [u'tak'],
    u'en': [u'th', u'ough'],
    u'fr': [u'qu', u'aie', u'eau', u'oix'],
    u'de': [u'ie', u'dsch', u'ig', u'ich', u'ei'],
    u'pl': [u'czy'],
  }

  """
  Combined list of pronouns, prepositions and conjunctions
  """
  words = {
    u'de': [
      u'über',
      u'oben',
      u'nach',
      u'gegen',
      u'unter',
      u'um',
      u'wie',
      u'bei',
      u'vor',
      u'hinter',
      u'unten',
      u'unter',
      u'neben',
      u'zwischen',
      u'darüber hinaus',
      u'aber',
      u'durch',
      u'trotz',
      u'nach unten',
      u'während',
      u'ausgenommen',
      u'für',
      u'von',
      u'in',
      u'innen',
      u'in',
      u'in der Nähe von',
      u'nächste',
      u'von',
      u'auf',
      u'gegenüber',
      u'heraus',
      u'außerhalb',
      u'pro',
      u'plus',
      u'um',
      u'seit',
      u'als',
      u'durch',
      u'bis',
      u'zu',
      u'gegen',
      u'unter',
      u'im Gegensatz zu',
      u'bis',
      u'hinauf',
      u'durch',
      u'mit',
      u'innerhalb',
      u'ohne',
      u'zwei Wörter',
      u'gemäß',
      u'wegen',
      u'nahe an',
      u'durch',
      u'bis auf',
      u'weit entfernt',
      u'innerhalb',
      u'statt',
      u'in der Nähe von',
      u'neben',
      u'außerhalb von',
      u'vor',
      u'drei Wörter',
      u'soweit',
      u'sowie',
      u'zusätzlich zu',
      u'vor',
      u'trotz',
      u'im Namen von',
      u'oben auf',
      u'ueber',
      u'darueber hinaus',
      u'fuer',
      u'gegenueber',
      u'ich',
      u'mich',
      u'mir',
      u'meiner',
      u'mein',
      u'du',
      u'dich',
      u'dir',
      u'deiner',
      u'dein',
      u'er',
      u'ihn',
      u'ihm',
      u'seiner',
      u'sein',
      u'es',
      u'es',
      u'ihm',
      u'seiner',
      u'sein',
      u'sie',
      u'ihr',
      u'ihrer',
      u'wir',
      u'uns',
      u'unser',
      u'ihr',
      u'euch',
      u'euch',
      u'euer',
      u'euer',
      u'sie',
      u'ihnen',
      u'ihrer',
      u'ihr',
      u'sie',
      u'ihnen',
      u'ihrer',
      u'ihr',
      u'aber',
      u'beziehungsweise',
      u'denn',
      u'oder',
      u'sondern',
      u'und',
      u'als',
      u'bevor',
      u'bis',
      u'dass',
      u'damit',
      u'nachdem',
      u'ob',
      u'if',
      u'obwohl',
      u'seitdem',
      u'sobald',
      u'sofern',
      u'as',
      u'soweit',
      u'sowie',
      u'während',
      u'weil',
      u'wenn',
      u'wie',
      u'wo',
    ],

    u'es': [
      u'a',
      u'ante',
      u'alrededor de',
      u'bajo',
      u'con',
      u'contra',
      u'de',
      u'desde',
      u'debajo de',
      u'en',
      u'entre',
      u'encima de',
      u'frente a',
      u'fuera de',
      u'hacia',
      u'hasta',
      u'por',
      u'detrás de',
      u'según',
      u'sin',
      u'sobre',
      u'tras',
      u'para',
      u'yo',
      u'me',
      u'mío',
      u'míos',
      u'mía',
      u'mías',
      u'mí',
      u'conmigo',
      u'tú',
      u'te',
      u'tuyo',
      u'tuyos',
      u'tuya',
      u'tuyas',
      u'ti',
      u'contigo',
      u'vos',
      u'con vos',
      u'usted',
      u'lo',
      u'la',
      u'se',
      u'le',
      u'se',
      u'suyo',
      u'suyos',
      u'suya',
      u'suyas',
      u'usted',
      u'con usted',
      u'él',
      u'ella',
      u'ello',
      u'él',
      u'ella',
      u'ello',
      u'sí',
      u'con él',
      u'ella',
      u'ello',
      u'consigo',
      u'nosotros',
      u'nosotras',
      u'nos',
      u'nuestro',
      u'nuestros',
      u'nuestra',
      u'nuestras',
      u'nosotros',
      u'nosotras',
      u'con nosotros',
      u'nosotras',
      u'vosotros',
      u'vosotras',
      u'os',
      u'vuestro',
      u'vuestros',
      u'vuestra',
      u'vuestras',
      u'vosotros',
      u'vosotras',
      u'con vosotros',
      u'vosotras',
      u'ustedes',
      u'los',
      u'las',
      u'se',
      u'les',
      u'se',
      u'suyo',
      u'suyos',
      u'suya',
      u'suyas',
      u'ustedes',
      u'con ustedes',
      u'ellos',
      u'ellas',
      u'ellos',
      u'ellas',
      u'sí',
      u'con ellos',
      u'ellas',
      u'consigo',
      u'y',
      u'e',
      u'ni',
      u'o',
      u'u',
      u'o bien',
      u'pero',
      u'mas',
      u'aunque',
      u'sin embargo',
      u'no obstante',
      u'por lo demás',
      u'excepto',
      u'es decir',
      u'esto es',
      u'porque',
      u'pues',
      u'puesto que',
      u'ya que',
      u'si',
      u'con tal de que',
      u'siempre que',
      u'como',
    ],

    u'en': [
      u'aboard',
      u'about',
      u'above',
      u'absent',
      u'across',
      u'cross',
      u'after',
      u'against',
      u'along',
      u'alongside',
      u'amid',
      u'amidst',
      u'among',
      u'amongst',
      u'apropos',
      u'apud',
      u'around',
      u'round',
      u'as',
      u'astride',
      u'at',
      u'atop',
      u'bar',
      u'before',
      u'afore',
      u'B4',
      u'behind',
      u'ahind',
      u'below',
      u'ablow',
      u'beneath',
      u'beside',
      u'besides',
      u'between',
      u'atween',
      u'beyond',
      u'ayond',
      u'but',
      u'by',
      u'chez',
      u'circa',
      u'come',
      u'dehors',
      u'despite',
      u'spite',
      u'down',
      u'during',
      u'except',
      u'for',
      u'from',
      u'in',
      u'inside',
      u'into',
      u'less',
      u'like',
      u'minus',
      u'near',
      u'nearer',
      u'anear',
      u'notwithstanding',
      u'of',
      u'off',
      u'on',
      u'onto',
      u'opposite',
      u'out',
      u'outen',
      u'outside',
      u'over',
      u'pace',
      u'past',
      u'per',
      u'plus',
      u'post',
      u'pre',
      u'pro',
      u'qua',
      u're',
      u'sans',
      u'save',
      u'sauf',
      u'short',
      u'since',
      u'sithence',
      u'than',
      u'through',
      u'thru',
      u'throughout',
      u'thruout',
      u'till',
      u'to',
      u'toward',
      u'under',
      u'underneath',
      u'unlike',
      u'until',
      u'til',
      u'unto',
      u'up',
      u'upon',
      u'upside',
      u'versus',
      u'via',
      u'vice',
      u'with',
      u'within',
      u'without',
      u'worth',
      u'I',
      u'you',
      u'he',
      u'she',
      u'it',
      u'we',
      u'they',
      u'me',
      u'him',
      u'her',
      u'us',
      u'them',
      u'I',
      u'you',
      u'he',
      u'she',
      u'it',
      u'we',
      u'they',
      u'what',
      u'who',
      u'me',
      u'him',
      u'her',
      u'it',
      u'us',
      u'you',
      u'them',
      u'whom',
      u'mine',
      u'yours',
      u'his',
      u'hers',
      u'ours',
      u'theirs',
      u'this',
      u'that',
      u'these',
      u'those',
      u'who',
      u'whom',
      u'which',
      u'what',
      u'whose',
      u'whoever',
      u'whatever',
      u'whichever',
      u'whomever',
      u'who',
      u'whom',
      u'whose',
      u'which',
      u'that',
      u'what',
      u'whatever',
      u'whoever',
      u'whomever',
      u'whichever',
      u'myself',
      u'yourself',
      u'himself',
      u'herself',
      u'itself',
      u'ourselves',
      u'themselves',
      u'Each',
      u'other',
      u'one',
      u'another',
      u'Anything',
      u'everybody',
      u'another',
      u'each',
      u'few',
      u'many',
      u'none',
      u'some',
      u'all',
      u'any',
      u'anybody',
      u'anyone',
      u'everyone',
      u'everything',
      u'no',
      u'one',
      u'nobody',
      u'nothing',
      u'none',
      u'other',
      u'others',
      u'several',
      u'somebody',
      u'someone',
      u'something',
      u'most',
      u'enough',
      u'little',
      u'more',
      u'both',
      u'either',
      u'neither',
      u'one',
      u'much',
      u'such',
      u'and',
      u'or',
      u'but',
      u'nor',
      u'so',
      u'for',
      u'yet',
      u'after',
      u'although',
      u'as',
      u'as if',
      u'as long as',
      u'because',
      u'before',
      u'even if',
      u'even though',
      u'once',
      u'since',
      u'so that',
      u'though',
      u'till',
      u'unless',
      u'until',
      u'what',
      u'when',
      u'whenever',
      u'wherever',
      u'whether',
      u'while',
    ],
  }

  """
  The spoken languages in each country
  """
  country_langs = {
    u'US': u'en',
    u'UK': u'en',
    u'AU': u'en',
  }